### ISSUE TITLE
`JsonIOException` when calling `getDocument` in 5.18.0

### ISSUE THREAD

**Issue by ikurek** [Synerise/android-sdk#14]
We have encountered an error after updating to `5.18.0`. When `Content.getDocument(String)` call is executed, Synerise SDK invokes `onFailureListener` with `ApiError` wrapping GSON exception:

`com.google.gson.JsonIOException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.synerise.sdk.a118`

I'm unable to investigate further, since SDK source is not available, but the same call is executed correctly in SDK versions 5.17.0 and earlier.

**Comment by konned** [comment]
Nothing has changed regarding Content module between those versions. I will take a look at it. Are you encountering this problem on every call?

**Comment by ikurek** [comment]
As far as I can tell, yes - I've tested a few and they all seem to fail on `5.18.0` and work on `5.17.0`

**Comment by konned** [comment]
Try adding: android.enableR8.fullMode=false to your gradle.properties.

**Comment by ikurek** [comment]
We already have that property set to false 😞

**Comment by ikurek** [comment]
I've tried it, without any luck - the error still persists and I still see `Class name: com.synerise.sdk.a118` in the error log 🤔

**Comment by konned** [comment]
Issue was solved in 5.18.1
