### ISSUE TITLE
IApiCalls don't expose synchronous or stream methods

### ISSUE THREAD

**Issue by micHar** [Synerise/android-sdk#2]
All the remote calls are encapsulated in an IApiCall which can only be called with your asynchronous callbacks solution (onSubscribe etc). I would like to excecute them as a part of my RxJava chains, but you make it harder than necessary by not exposing the observables (even though you use them in your source code internally) or at least providing a synchronous access. It would be great if you exposed that in IApiCall interface.

**Comment by mskx42** [comment]
Note, that returning observables directly would force our SDK users to use RxJava2 itself in their projects, which is never a good practice. We do not make it harder than necessary, trust me. Nevertheless, we may give RxJava2 some special treatment and grant our users an access to the wrapped observables in the next major release.

**Comment by micHar** [comment]
You don't have to enforce anything. You could just expose multiple options, this should be relatively easy. All it really takes is separation of the action performed by IAPiCall from the method of handling it (sync/callbacks/rx). Typically such SDK's expose synchronous methods and let user handle asynchronous access the way he handles it in application, because there are dozens of options. Callbacks would generally be optional. 

I wrote an quick wrapper for your IApiCalls, thankfully my projects utilises Kotlin, because without higher order functions it would require a lot of ugly boilerplate to handle. Nevertheless I would kindly ask you to consider expanding your API for more flexibility - rx is not really necessary, but I feel that synchronous access is.
