### ISSUE TITLE
'eventCreateTime' semantic has changed

### ISSUE THREAD

**Issue by marecik16** [Synerise/android-sdk#3]
Yesterday I upgraded SDK from 3.3.13 to 3.6.6.

I was supprised, that the semantic of 'eventCreateTime' has changed. In the previous version, 'eventCreateTime' meant time, when the event was ~registered in the System and it was slightly later than event's reference 'time'. In particular, when a mobile had no access to the internet, the difference between 'time' and 'eventCreateTime'  meant (more or less) the time duration without internet connection. That behaviour helps me track when the events were really sent, especially if I group them in batches and do not flush instantly.

In the new version 'eventCreateTime' is EXACTLY the same as event's 'time' and it seems to be completely redundant.

Is it a bug or an intented change?

**Comment by konned** [comment]
It was an intended change due to inconsistency in data.
