### ISSUE TITLE
HMS push kit support

### ISSUE THREAD

**Issue by hms-dtse-dxb** [Synerise/android-sdk#4]
Hi, do you guys have any plans to add support for Huawei push kit https://developer.huawei.com/consumer/en/hms/huawei-pushkit.
Thanks.

**Comment by konned** [comment]
We are working on providing support for Huawei and HMS in our SDK and system.

**Comment by megaacheyounes** [comment]
Thats great news, can you tell me when it will be available?

**Comment by megaacheyounes** [comment]
That's great news, can you tell us when it will be available?

**Comment by konned** [comment]
We are now supporting HMS. For more information please visit: https://help.synerise.com/developers/android-sdk/huawei-integration/
