### ISSUE TITLE
Error when setting Picasso Singleton Instance

### ISSUE THREAD

**Issue by SakisBoridis** [Synerise/android-sdk#5]
Hello, I am trying to implement the synerise sdk in my app but I am having issues with the Picasso sdk.

In my Application class onCreate I call:
`Picasso picasso = new Picasso.Builder(getApplicationContext()).downloader(new OkHttp3Downloader(client)).build();
Picasso.setSingletonInstance(picasso);
`

So, when I call:
`Synerise.Builder.with(this, clientApiKey, appId).build();`
in the same onCreate method as stated in the documentation, then I get the following error:
`Caused by: java.lang.IllegalStateException: Singleton instance already exists.
        at com.squareup.picasso.Picasso.setSingletonInstance(Picasso.java:701)
        at com.synerise.sdk.injector.b.a(InjectorSDK.java:99)
        at com.synerise.sdk.injector.b.<init>(InjectorSDK.java:33)
        at com.synerise.sdk.injector.Injector.init(Injector.java:3)
        at com.synerise.sdk.core.Synerise.b(Synerise.java:8)
        at com.synerise.sdk.core.Synerise.a(Synerise.java:1)
        at com.synerise.sdk.core.Synerise$Builder.build(Synerise.java:1)`

Inside InjectorSDK() method you configurePicasso preventing the users to also do the same if needed. How can this be bypassed? Or is it possible for synerise not to call setSingletonInstance() in order to set the instance globally?

**Comment by konned** [comment]
Thank you for information. We will introduce changes that would solve that problem in future version that will be available early in June.

**Comment by SakisBoridis** [comment]
Thanks a lot for your quick response. I guess it is a reasonable request to expect from an SDK not to restrict users to configure Picasso instance globally themselves. I will be waiting for your update.

**Comment by konned** [comment]
Yes I agree. That's a pity that you cannot update picasso's singleton

**Comment by konned** [comment]
FIxed in 3.8.0
